import Link from "next/link";

export const metadata = { title: "Disclaimer — Sundeas AI" };

const sections = [
  {
    title: "Not financial advice",
    body: "Sundeas AI is an educational platform. Nothing on this website, in the app, or in any communication from Sundeas AI (including AI-generated insights, portfolio analysis, market commentary, and email briefings) constitutes personalised financial advice, investment advice, or a recommendation to buy, sell, or hold any financial instrument. All content is provided for general informational and educational purposes only.",
  },
  {
    title: "Not regulated",
    body: "Sundeas AI is not authorised or regulated by the Financial Conduct Authority (FCA) or any other financial regulatory body. We do not provide regulated financial advice or services. If you require personalised financial advice, you should consult a qualified independent financial adviser who is authorised and regulated by the FCA.",
  },
  {
    title: "No liability for investment decisions",
    body: "You are solely responsible for any investment decisions you make. Sundeas AI, its founders, employees, and agents accept no liability whatsoever for any loss or damage — direct, indirect, or consequential — arising from decisions made in reliance on content provided by this platform, including AI-generated insights. The value of investments can go down as well as up, and you may get back less than you invest.",
  },
  {
    title: "Data accuracy",
    body: "Portfolio data, prices, and valuations displayed on Sundeas AI are sourced from third-party providers (including Trading 212) and may be delayed, inaccurate, or incomplete. Do not rely on prices or valuations shown on this platform for the purpose of making trading decisions. Always verify data independently before acting on it.",
  },
  {
    title: "AI-generated content",
    body: "Market insights and portfolio commentary are generated by an artificial intelligence model. AI outputs may be incorrect, outdated, or misleading. They are not reviewed by a qualified financial professional before delivery. Sundeas AI makes no warranty as to the accuracy, completeness, or fitness for purpose of any AI-generated content.",
  },
  {
    title: "Past performance",
    body: "Any reference to past performance, historical returns, or backtested data is not a reliable indicator of future results. Markets are unpredictable and investing carries risk.",
  },
  {
    title: "Third-party links and services",
    body: "Sundeas AI may contain links to or integrations with third-party services (including Trading 212 and others). We are not responsible for the content, accuracy, or practices of any third-party service. Any affiliate links or referrals are disclosed and do not influence the educational content we provide.",
  },
  {
    title: "Your responsibility",
    body: "By using Sundeas AI, you acknowledge that you have read and understood this disclaimer. You agree that you will not hold Sundeas AI or its founders liable for any losses incurred as a result of using information provided on this platform. You accept that investing involves risk and that you should only invest money you can afford to lose.",
  },
];

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-[var(--background)]">
      {/* Simple header */}
      <header className="border-b border-[var(--border)] bg-[var(--surface)]">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-4">
          <Link href="/" className="text-base font-bold tracking-tight text-[var(--foreground)]">
            Sundeas<span className="text-[var(--accent)]">.</span>AI
          </Link>
          <Link href="/" className="text-sm text-[var(--muted)] hover:text-[var(--foreground)]">
            ← Back
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-16">
        <div className="mb-10">
          <h1 className="text-3xl font-bold text-[var(--foreground)]">Disclaimer</h1>
          <p className="mt-3 text-sm text-[var(--muted)]">Last updated: April 2026</p>
          <p className="mt-4 text-[var(--muted)] leading-relaxed">
            Please read this disclaimer carefully before using Sundeas AI. By accessing or using this
            platform you confirm that you have read, understood, and agreed to the terms set out below.
          </p>
        </div>

        <div className="flex flex-col gap-8">
          {sections.map(({ title, body }) => (
            <div key={title}>
              <h2 className="mb-2 text-base font-semibold text-[var(--foreground)]">{title}</h2>
              <p className="text-sm leading-relaxed text-[var(--muted)]">{body}</p>
            </div>
          ))}
        </div>

        <div className="mt-12 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-6 text-sm leading-relaxed text-[var(--muted)]">
          If you have any questions about this disclaimer, please contact us at{" "}
          <a href="mailto:samuele.perrone@gmail.com" className="text-[var(--accent)] hover:underline">
            samuele.perrone@gmail.com
          </a>.
        </div>
      </main>
    </div>
  );
}
